go_import_path: github.com/elastos/Elastos.ELA
language: go
go:
  - "1.13"
sudo: false
install:
  - go get -u github.com/mgechev/revive
script:
  - go test `go list ./... | grep -v benchmark` -short
  - make
  - make dns
  - make datagen
  - ./util.sh test
  - revive -config .revive.toml -formatter friendly -exclude vendor/... $(go list ./...)
