version : "3.2"
services:

  ela-mainchain:
    container_name: ela-mainchain
    image: ela-mainchain
    build:
      context: ela-mainchain
    ports:
      - 20333-20338:20333-20338
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20334/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-sidechain-did:
    container_name: ela-sidechain-did
    image: ela-sidechain-did
    depends_on:
      - ela-mainchain
    build:
      context: ela-sidechain/did
    ports:
      - 20604-20608:20604-20608
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20604/api/v1/node/connectioncount"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-sidechain-token:
    container_name: ela-sidechain-token
    image: ela-sidechain-token
    depends_on:
      - ela-mainchain
    build:
      context: ela-sidechain/token
    ports:
      - 20614-20618:20614-20618
    healthcheck:
      test: ["CMD", "curl", "-H", "Content-Type:application/json", "-H", "Accept:application/json", "--data", "'{\"method\":\"getbestblockhash\"}'", "http://localhost:20616"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-arbitrator-1:
    container_name: ela-arbitrator-1
    image: ela-arbitrator
    depends_on:
      - ela-mainchain
      - ela-sidechain-did
    build:
      context: ela-arbitrator/arbitrator-1
    ports:
      - 10336:10336
      - 10338:10338
    networks:
      - blockchain
    tty: true

  ela-arbitrator-2:
    container_name: ela-arbitrator-2
    image: ela-arbitrator
    depends_on:
      - ela-mainchain
      - ela-sidechain-did
    build:
      context: ela-arbitrator/arbitrator-2
    ports:
      - 11336:11336
      - 11338:11338
    healthcheck:
      test: ["CMD", "curl", "-H", "Content-Type:application/json", "-H", "Accept:application/json", "--data", "'{\"method\":\"getmainchainblockheight\"}'", "http://localhost:11336"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-wallet-service:
    container_name: ela-wallet-service
    image: ela-wallet-service
    depends_on:
      - ela-mysql
      - ela-mainchain
      - ela-sidechain-did
    build:
      context: restful-services/wallet-service
    ports:
      - 8091:8091
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true   
    
  ela-did-service:
    container_name: ela-did-service
    image: ela-did-service
    depends_on:
      - ela-mainchain
      - ela-sidechain-did
    build:
      context: restful-services/did-service
    ports:
      - 8092:8092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/api/1/currHeight"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true  

  ela-mysql:
    container_name: ela-mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=ws
      - MYSQL_USER=elastos
      - MYSQL_PASSWORD=12345678
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-api-misc:
    container_name: ela-api-misc
    image: ela-api-misc
    depends_on:
      - ela-mysql
    build:
      context: restful-services/api-misc
    ports:
      - 8093:8093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8093/api/1/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blockchain
    tty: true

  ela-hive-ipfs-peer-1:
    container_name: ela-hive-ipfs-peer-1
    image: ela-hive-ipfs-peer-1
    build:
      context: ela-hive/hive-ipfs
      dockerfile: Dockerfile-peer-1
    ports:
      - 38080:8080 
    networks:
      - hive
    tty: true

  ela-hive-ipfs-peer-2:
    container_name: ela-hive-ipfs-peer-2
    image: ela-hive-ipfs-peer-2
    build:
      context: ela-hive/hive-ipfs
      dockerfile: Dockerfile-peer-2
    ports:
      - 48080:8080
    networks:
      - hive
    tty: true

  ela-hive-cluster-master:
    container_name: ela-hive-cluster-master
    image: ela-hive-cluster-master
    depends_on:
      - ela-hive-ipfs-peer-1
      - ela-hive-ipfs-peer-2
    build:
      context: ela-hive/hive-cluster
      dockerfile: Dockerfile-master
    ports:
      - 9094-9096:9094-9096
    networks:
      - hive
    tty: true

  ela-hive-cluster-slave:
    container_name: ela-hive-cluster-slave
    image: ela-hive-cluster-slave
    depends_on:
      - ela-hive-ipfs-peer-1
      - ela-hive-ipfs-peer-2
      - ela-hive-cluster-master
    build:
      context: ela-hive/hive-cluster
      dockerfile: Dockerfile-slave
    ports:
      - 49094-49096:9094-9096
    networks:
      - hive
    tty: true

networks:
  blockchain:
  hive:

